language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t xwa130/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xwa130/react-test npm test

after_success:
  - docker build -t xwa130/multi-client ./client
  - docker build -t xwa130/multi-nginx ./nginx
  - docker build -t xwa130/multi-server ./server
  - docker build -t xwa130/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push xwa130/multi-client
  - docker push xwa130/multi-nginx
  - docker push xwa130/multi-server
  - docker push xwa130/multi-worker